nodeLinker: node-modules

# Utilise le cache local dans .yarn/cache
enableGlobalCache: false

# Garde les logs détaillés en cas d'erreur
# logLevel: info

# Active l'installation automatique des peerDependencies manquants
preferInteractive: true

# Réduit les messages superflus lors de l'installation
enableTelemetry: false